[GH page] Improve texts in index.html
rerrahkr/BambooTracker pull request #331
Opened 2021-02-16 18:47 UTC by freq-mod

less awkward, I guess

2021-02-16 18:51 UTC, OPNA2608 requested changes

2021-02-16 18:51 UTC, OPNA2608 commented on index.html
> +                  <p class="card-text">Entry notes with your MIDI device is possible.</p>
Maybe
```suggestion
                  <p class="card-text">Note input via a MIDI device is supported.</p>
```

2021-02-16 19:09 UTC, freq-mod commented on index.html
> +                  <p class="card-text">Entry notes with your MIDI device is possible.</p>
thanks

2021-02-17 10:26 UTC, merged

2021-02-17 10:27 UTC, rerrahkr commented
Thanks for your contribution!
I just made a simple web page, so feel free to edit it more if you can create a clearer layout or content.

2021-02-17 10:42 UTC, freq-mod commented
Will certainly think about it, there is some room for improvement, the more I look at it...